package com.mastercard.code.challenge.service;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import com.mastercard.code.challenge.model.Address;

public interface RandomGeneratorService {
	
	public static final  List<String> COUNTRY_CODES = Collections.unmodifiableList(Arrays.asList("USA", "CAN", "MEX", "NLD"));
	public static final  List<String> COUNTRIES = Collections.unmodifiableList(Arrays.asList("United States Of America", "Canada", "México", "Netherlands"));
	
	public static final  List<String> USA_STATE_CODES = Collections.unmodifiableList(Arrays.asList("AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"));
	public static final  List<String> USA_STATES = Collections.unmodifiableList(Arrays.asList("Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"));
	public static final  List<String> USA_CITIES = Collections.unmodifiableList(Arrays.asList("Montgomery","Juneau","Phoenix","Little Rock","Sacramento","Denver","Hartford","Dover","Tallahassee","Atlanta","Honolulu","Boise","Springfield","Indianapolis","Des Moines","Topeka","Frankfort","Baton Rouge","Augusta","Annapolis","Boston","Lansing","St. Paul","Jackson","Jefferson City","Helena","Lincoln","Carson City","Concord","Trenton","Santa Fe","Albany","Raleigh","Bismarck","Columbus","Oklahoma City","Salem","Harrisburg","Providence","Columbia","Pierre","Nashville","Austin","Salt Lake City","Montpelier","Richmond","Olympia","Charleston","Madison","Cheyenne"));
	public static final  List<String> USA_STREET_TYP = Collections.unmodifiableList(Arrays.asList("Ln","Pl","CIR","BLVD","WAY", "AVE", "PARK", "RD", "DR"));
	public static final  List<String> USA_STREETS = Collections.unmodifiableList(Arrays.asList("PO BOX", "Second","Third","First","Fourth","Park", "5th", "Main", "6th", "Oak", "7th", "Pine", "Maple", "Cedar", "8th", "Elm", "View", "Washington", "9th", "Lake", "Hill"));
	
	public static final  List<String> CAN_STATE_CODES = Collections.unmodifiableList(Arrays.asList("AB", "BC", "MB", "NB", "NL", "NS", "NT", "NU", "ON", "PE", "QC", "SK", "YT"));
	public static final  List<String> CAN_STATES = Collections.unmodifiableList(Arrays.asList("Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland and Labrador", "Nova Scotia", "Northwest Territories", "Nunavut", "Ontario", "Prince Edward Island", "Quebec", "Saskatchewan", "Yukon"));
	public static final  List<String> CAN_CITIES = Collections.unmodifiableList(Arrays.asList("Edmonton", "Victoria", "Winnipeg", "Fredericton", "St. John's", "Halifax", "Yellowknife", "Iqaluit", "Toronto", "Charlottetown", "Québec", "Regina", "Whitehorse"));
	public static final  List<String> CAN_STREET_TYP = Collections.unmodifiableList(Arrays.asList("Access","Acres","Aire","Alley","Allée","Autoroute","Avenue","Avenue","Bay","Beach","Bend","Bloc","Block","Boulevard","Boulevard","Bourg","Barrage","Brook","By-pass","Byway","Centre","Campus","Cape","Carré","Carrefour","Cul-de-sac","Cercle","Chemin","Chase","Circle","Circuit","Close","Common","Concession","Côte","Cour","Cours","Cove","Crescent","Crest","Corners","Croft","Croissant","Crossing","Crossroads","Court","Centre","Dale","Dell","Desserte","Diversion","Downs","Drive","Droit de passage","Échangeur","End","Esplanade","Estate","Expressway","Extension","Farm","Field","Forest","Front","Freeway","Gate","Gardens","Glade","Glen","Green","Grounds","Grove","Harbour","Haven","Heath","Highlands","Hill","Hollow","Heights","Highway","Île","Impasse","Inlet","Island","Key","Knoll","Landing","Lane","Laneway","Line","Link","Lookout","Limits","Loop","Mall","Manor","Maze","Meadow","Mews","Montée","Moor","Mount","Mountain","Orchard","Parade","Parc","Passage","Path","Peak","Pines","Park","Parkway","Place","Place","Plateau","Plaza","Pointe","Port","Promenade","Point","Pathway","Private","Quai","Quay","Ramp","Rang","Road","Rond point","Reach","Range","Ridge","Rise","Ruelle","Route","Row","Route","Right of way","Rue","Ruisseau","Run","Section","Sentier","Sideroad","Square","Street","Stroll","Subdivision","Terrace","Thicket","Townline","Towers","Trace","Trail","Turnabout","Trunk","Terrasse","Vale","Via","View","Villas","Village","Vista","Voie","Walk","Way","Wharf","Wood","Wynd"));
	public static final  List<String> CAN_STREETS = Collections.unmodifiableList(Arrays.asList("P.O. BOX", "Second","Third","First","Fourth","Park", "5th", "Main", "6th", "Oak", "7th", "Pine", "Maple", "Cedar", "8th", "Elm", "View", "Washington", "9th", "Lake", "Hill"));
	
	public static final  List<String> MEX_STATE_CODES = Collections.unmodifiableList(Arrays.asList("AG","BC","BS","CH","CL","CM","CO","CS","DF","DG","GR","GT","HG","JA","ME","MI","MO","NA","NL","OA","PB","QE","QR","SI","SL","SO","TB","TL","TM","VE","YU","ZA"));
	public static final  List<String> MEX_STATES = Collections.unmodifiableList(Arrays.asList("Aguascalientes", "Baja California", "Baja California Sur", "Chihuahua", "Colima", "Campeche", "Coahuila", "Chiapas", "Durango", "Guerrero", "Guanajuato", "Hidalgo", "Jalisco", "México State", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", "Sinaloa", "San Luis Potosí", "Sonora", "Tabasco", "Tlaxcala", "Tamaulipas", "Veracruz", "Yucatán", "Zacatecas","Zacatecas"));
	public static final  List<String> MEX_CITIES = Collections.unmodifiableList(Arrays.asList("Aguascalientes", "Mexicali", "La Paz", "Chihuahua", "Colima", "Campeche", "Saltillo", "Tuxtla Gutiérrez", "Durango", "Chilpancingo", "Guanajuato", "Pachuca", "Guadalajara", "Toluca", "Morelia", "Cuernavaca", "Tepic", "Monterrey", "Oaxaca", "Puebla", "Querétaro", "Chetumal", "Culiacán", "San Luis Potosí", "Hermosillo", "Villahermosa", "Tlaxcala", "Ciudad Victoria", "Xalapa", "Mérida", "Zacatecas"));
	public static final  List<String> MEX_STREETS = Collections.unmodifiableList(Arrays.asList("P.O. BOX", "Alvaro Obregón", "Prado Norte", "Callejón de Belleza", "Reforma", "Madero", "Mesones", "Madero Street", "Paseo de la Reforma", "Viaducto Miguel Aléman", "Eje Central", "Eje vial", "Avenida Bucareli", "Avenida Alvaro Obregón", "Amsterdam Avenue", "Avenida de los insurgentes", "Avenida Juárez", "Avenida Presidente Masaryk"));

	public static final  List<String> NLD_STATE_CODES = Collections.unmodifiableList(Arrays.asList("DR", "FL", "FR", "GE", "GR", "LI", "NB", "NH", "OV", "UT", "ZE,", "ZH"));
	public static final  List<String> NLD_STATES = Collections.unmodifiableList(Arrays.asList("Drenthe", "Flevoland", "Friesland", "Gelderland", "Groningen", "Limburg", "North Brabant", "North Holland", "Overijssel", "South Holland", "Utrecht", "Zeeland" ));
	public static final  List<String> NLD_CITIES = Collections.unmodifiableList(Arrays.asList("Assen", "Lelystad", "Leeuwarden", "Arnhem", "Groningen", "Maastricht", "s-hertogenbosch", "Haarlem", "Zwolle", "The Hague", "MiddelBurg"));
	public static final  List<String> NLD_STREET_TYP = Collections.unmodifiableList(Arrays.asList("bocht", "laan", "rijbaan", "beurs", "pad", "singel", "dreef", "plaats", "steeg", "gracht", "plantsoen", "straat", "kade", "poort", "weg"));
	public static final  List<String> NLD_STREETS = Collections.unmodifiableList(Arrays.asList("PO BOX", "Bankastraat", "Gasthuislaan", "Koningsstraat", "Molstraat", "Paleisstraat", "Schoolstraat", "Voorstraat", "Bloemstraat", "Herenstraat", "Kruisstraat", "Nieuwestraat", "Parkstraat", "Sportlaan", "Westeinde", "Dorpstraat", "Hoogstraat", "Langstraat", "Noordeinde", "Prinsestraat", "Tuinstraat", "Zeestraat", "Energieweg", "Kerkstraat", "Molenstraat", "Oosteinde", "Raadhuisstraat", "Visstraat", "Zuideinde"));

	public Address getRandomAddress();

}
